### ISSUE TITLE
SCS fails to install on Julia 1.5

### ISSUE THREAD

**Issue by steven-varga** [jump-dev/SCS.jl#194] opened 2020-08-04 21:38 UTC
Hello,
can someone point out what I could be doing wrong? pgk> add SCS or build SCS fails :(
best:
steven

```
(@v1.5) pkg> build SCS
   Building SCS → `~/.julia/packages/SCS/28Svy/deps/build.log`
┌ Error: Error building `SCS`: 
│ ERROR: LoadError: LibraryProduct(nothing, ["libscsindir"], :indirect, "Prefix(/home/steven/.julia/packages/SCS/28Svy/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] write_deps_file(::String, ::Array{LibraryProduct,1}; verbose::Bool, isolate::Bool) at /home/steven/.julia/packages/BinaryProvider/U2dKK/src/Products.jl:419
│  [3] top-level scope at /home/steven/.julia/packages/SCS/28Svy/deps/build.jl:94
│  [4] include(::String) at ./client.jl:457
│  [5] top-level scope at none:5
│ in expression starting at /home/steven/.julia/packages/SCS/28Svy/deps/build.jl:94
└ @ Pkg.Operations ~/src/julia/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:942
```
Path is clearly there:
```
ls /home/steven/.julia/packages/SCS/28Svy/deps/usr
bin  downloads	lib  logs  manifests
```

```
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libimf
  LLVM: libLLVM-9.0.1 (ORCJIT, broadwell
```

**Comment by odow** [comment] 2020-08-04 23:31
Github changed their API: https://discourse.julialang.org/t/pkg-downtime-incident/44288

What happens if you go `using SCS`? We don't actually need to run `build.jl` on Julia 1.3+.

**Comment by steven-varga** [comment] 2020-08-05 02:06
Thanks for the quick reply. I manually removed SCS then tried `pkg> add SCS` then  doing `using SCS` results in the error message at the bottom. So I commented out the lines responsible for the error message, which lead me to `LoadError: LoadError: UndefVarError: direct not defined` in 
`.julia/packages/SCS/28Svy/src/c_wrapper.jl:83` reading the relevant (meta)code section the `SCS.direct` is missing, and should be generated with `build.jl` 
Any ideas?  

```
julia> using SCS
[ Info: Precompiling SCS [c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13]
ERROR: LoadError: SCS not properly installed. Please run Pkg.build("SCS") and restart julia
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] top-level scope at /home/steven/.julia/packages/SCS/28Svy/src/SCS.jl:6
 [3] include(::Function, ::Module, ::String) at ./Base.jl:380
 [4] include(::Module, ::String) at ./Base.jl:368
 [5] top-level scope at none:2
 [6] eval at ./boot.jl:331 [inlined]
 [7] eval(::Expr) at ./client.jl:467
 [8] top-level scope at ./none:3
in expression starting at /home/steven/.julia/packages/SCS/28Svy/src/SCS.jl:3
ERROR: Failed to precompile SCS [c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13] to /home/steven/.julia/compiled/v1.5/SCS/uaibp_ytu7M.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at ./loading.jl:1290
 [3] _require(::Base.PkgId) at ./loading.jl:1030
 [4] require(::Base.PkgId) at ./loading.jl:928
 [5] require(::Module, ::Symbol) at ./loading.jl:923


```

**Comment by votroto** [comment] 2020-08-05 13:24
A work-around is to build the libraries manually (as described in `README.md`), and setting the julia ENV variable before building `SCS.jl`.

**Comment by odow** [comment] 2020-08-05 13:35
You can probably try again now. I think Github reverted the change.

**Comment by kalmarek** [comment] 2020-08-05 14:02
> ```
> julia> using SCS
> [ Info: Precompiling SCS [c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13]
> ERROR: LoadError: SCS not properly installed. Please run Pkg.build("SCS") and restart julia
> Stacktrace:
>  [1] error(::String) at ./error.jl:33
>  [2] top-level scope at /home/steven/.julia/packages/SCS/28Svy/src/SCS.jl:6

@steven-varga It seems you're either using julia-1.2 or earlier (you don't, right?), or you forgot to unset `JULIA_SCS_LIBRARY_PATH` ? at least the code path is followed only in those cases:
https://github.com/jump-dev/SCS.jl/blob/6611207d8759cb4a7a1f8c10bcff606f0ccb471a/src/SCS.jl#L3

**Comment by votroto** [comment] 2020-08-05 14:17
On updated Julia 1.5:
```julia
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.0 (2020-08-01)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

julia> ENV["JULIA_SCS_LIBRARY_PATH"]
ERROR: KeyError: key "JULIA_SCS_LIBRARY_PATH" not found

julia> using SCS
ERROR: ArgumentError: Package SCS not found in current path:
- Run `import Pkg; Pkg.add("SCS")` to install the SCS package.

Stacktrace:
 [1] run_repl(::REPL.AbstractREPL, ::Any) at /build/julia/src/julia-1.5.0/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:288

(@v1.5) pkg> add SCS
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
  Installed Zlib_jll ── v1.2.11+15
  Installed Bzip2_jll ─ v1.0.6+3
Updating `~/.julia/environments/v1.5/Project.toml`
  [c946c3f1] + SCS v0.6.6
Updating `~/.julia/environments/v1.5/Manifest.toml`
  [6e4b80f9] + BenchmarkTools v0.5.0
  [b99e7846] + BinaryProvider v0.5.10
  [6e34b625] + Bzip2_jll v1.0.6+3
  [523fee87] + CodecBzip2 v0.7.2
  [944b1d66] + CodecZlib v0.7.0
  [cd3eb016] + HTTP v0.8.17
  [83e8ac13] + IniFile v0.5.0
  [682c06a0] + JSON v0.21.0
  [7d188eb4] + JSONSchema v0.3.1
  [b8f27783] + MathOptInterface v0.9.14
  [fdba3010] + MathProgBase v0.7.8
  [739be429] + MbedTLS v1.0.2
  [c8ffd9c3] + MbedTLS_jll v2.16.6+1
  [d8a4904e] + MutableArithmetics v0.2.10
  [bac558e1] + OrderedCollections v1.3.0
  [69de0a69] + Parsers v1.0.7
  [c946c3f1] + SCS v0.6.6
  [3bb67fe8] + TranscodingStreams v0.9.5
  [a5390f91] + ZipFile v0.9.2
  [83775a58] + Zlib_jll v1.2.11+15
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8ba89e20] + Distributed
  [b77e0a4c] + InteractiveUtils
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode

julia> using SCS
[ Info: Precompiling SCS [c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13]
ERROR: LoadError: SCS not properly installed. Please run Pkg.build("SCS") and restart julia
Stacktrace:
 [1] top-level scope at /home/votroto/.julia/packages/SCS/28Svy/src/SCS.jl:6
 [2] top-level scope at none:2
 [3] eval at ./boot.jl:331 [inlined]
in expression starting at /home/votroto/.julia/packages/SCS/28Svy/src/SCS.jl:3
ERROR: Failed to precompile SCS [c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13] to /home/votroto/.julia/compiled/v1.5/SCS/uaibp_dm1G8.ji.
Stacktrace:
 [1] run_repl(::REPL.AbstractREPL, ::Any) at /build/julia/src/julia-1.5.0/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:288

(@v1.5) pkg> build SCS
   Building SCS → `~/.julia/packages/SCS/28Svy/deps/build.log`
┌ Error: Error building `SCS`: 
│ ERROR: LoadError: LibraryProduct(nothing, ["libscsindir"], :indirect, "Prefix(/home/votroto/.julia/packages/SCS/28Svy/deps/usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] write_deps_file(::String, ::Array{LibraryProduct,1}; verbose::Bool, isolate::Bool) at /home/votroto/.julia/packages/BinaryProvider/U2dKK/src/Products.jl:419
│  [2] top-level scope at /home/votroto/.julia/packages/SCS/28Svy/deps/build.jl:94
│  [3] include(::String) at ./client.jl:457
│  [4] top-level scope at none:5
│ in expression starting at /home/votroto/.julia/packages/SCS/28Svy/deps/build.jl:94
└ @ Pkg.Operations /build/julia/src/julia-1.5.0/usr/share/julia/stdlib/v1.5/Pkg/src/Operations.jl:942

```
Whereas continuing with a custom SCS build 
```julia
julia> ENV["JULIA_SCS_LIBRARY_PATH"] = "/blahblah/scs/out"
"/blahblah/scs/out"

(@v1.5) pkg> build SCS
   Building SCS → `~/.julia/packages/SCS/28Svy/deps/build.log`

julia> using SCS
[ Info: Precompiling SCS [c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13]

```
And testing
```julia
blah blah blah...

    Testing SCS tests passed 
```

**Comment by votroto** [comment] 2020-08-05 14:34
Ok, after the patch by @odow it works from `master`.

```julia
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.0 (2020-08-01)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |

(@v1.5) pkg> add https://github.com/jump-dev/SCS.jl.git
   Updating git-repo `https://github.com/jump-dev/SCS.jl.git`
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
Updating `~/.julia/environments/v1.5/Project.toml`
  [c946c3f1] + SCS v0.7.0 `https://github.com/jump-dev/SCS.jl.git#master`
Updating `~/.julia/environments/v1.5/Manifest.toml`
  [6e4b80f9] + BenchmarkTools v0.5.0
  [b99e7846] + BinaryProvider v0.5.10
  [6e34b625] + Bzip2_jll v1.0.6+3
  [523fee87] + CodecBzip2 v0.7.2
  [944b1d66] + CodecZlib v0.7.0
  [e66e0078] + CompilerSupportLibraries_jll v0.3.3+0
  [cd3eb016] + HTTP v0.8.17
  [83e8ac13] + IniFile v0.5.0
  [682c06a0] + JSON v0.21.0
  [7d188eb4] + JSONSchema v0.3.1
  [b8f27783] + MathOptInterface v0.9.14
  [fdba3010] + MathProgBase v0.7.8
  [739be429] + MbedTLS v1.0.2
  [c8ffd9c3] + MbedTLS_jll v2.16.6+1
  [d8a4904e] + MutableArithmetics v0.2.10
  [4536629a] + OpenBLAS_jll v0.3.9+5
  [bac558e1] + OrderedCollections v1.3.0
  [69de0a69] + Parsers v1.0.7
  [c946c3f1] + SCS v0.7.0 `https://github.com/jump-dev/SCS.jl.git#master`
  [f4f2fc5b] + SCS_jll v2.1.2+0
  [3bb67fe8] + TranscodingStreams v0.9.5
  [a5390f91] + ZipFile v0.9.2
  [83775a58] + Zlib_jll v1.2.11+15
  [2a0f44e3] + Base64
  [ade2ca70] + Dates
  [8ba89e20] + Distributed
  [b77e0a4c] + InteractiveUtils
  [76f85450] + LibGit2
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [a63ad114] + Mmap
  [44cfe95a] + Pkg
  [de0858da] + Printf
  [3fa0cd96] + REPL
  [9a3f8284] + Random
  [ea8e919c] + SHA
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [2f01184e] + SparseArrays
  [10745b16] + Statistics
  [8dfed614] + Test
  [cf7118a7] + UUIDs
  [4ec0a83e] + Unicode

julia> using SCS
[ Info: Precompiling SCS [c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13]

```

**Comment by kalmarek** [comment] 2020-08-05 14:57
hmm... I can't reproduce it with scs-0.6.6...

could you try with empty DEPOT? something along
```
JULIA_DEPOT_PATH=/tmp/scs_try julia-1.5.0 --project=/tmp/scs_try -e 'using Pkg; Pkg.add("SCS"); Pkg.test("SCS");'
```
?
In the first log there is no `SCS_jll`, but that can be already installed in the correct version...

But despite claims to reproducibility no two systems run exactly the same, so I'm not very surprised ;)

**Comment by steven-varga** [comment] 2020-08-05 22:57
Thanks you all for the informative responses! Putting all the pieces together I concluded with SCS on a custom compiled julia with MKL:

1. SCS compiled from source with `make purge; make USE_OPENMP=1 BLAS64=1  DLONG=1 BLASLDFLAGS=-liomp5 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core out/libscsdir.so out/libscsindir.so`
installed to `/usr/local/lib`
2. in Julia 1.5.0 compiled against Intel MKL
   - set environment variable `ENV["JULIA_SCS_LIBRARY_PATH"]="/home/steven/src/scs/out/"`
   - installed SCS: `pkg> add SCS; build SCS`
   - ran test: `pkg> test SCS`

The original SCS  `make test` will fail when  `USE_OPENMP=1` set, I am not quite certain if because the test programs expect `libgomp.so` as opposed to `libiomp5.so` or for other reasons; nevertheless julia SCS test checked out with the exception of one. 
Thanks again!

**Comment by votroto** [comment] 2020-08-08 01:42
@kalmarek, You were right, I failed to remove `SCS_jll` properly. 

Doing it properly (using a clean DEPOT) fails in the expected manner, that is:
the build fails to create `deps.jl`, but (as you have said) it is unnecessary (skipped in `SCS.jl`) anyway.

The real problem is that `build.jl` calls `write_deps_file` with `isolate` set to `true` by default.
Unfortunately, while the "products" are "satisfied" with `isolate=false`, they fail to "satisfy" with `isloate=true`.

My guess is that something in Julia's string itnerpolation has changed between versions (or systems)
and the line in BinaryProvider https://github.com/JuliaPackaging/BinaryProvider.jl/blob/81f03dad25dfd76845f4fbc0eea1a383280f334c/src/Products.jl#L168 no longer works properly.

But since `SCS.jl` does not need the deps file anyway, probably just add the same version check into `build.jl`?

**Comment by kalmarek** [comment] 2020-08-08 07:59
@votroto thanks for digging into the issue; since you already know what is going on would you mind creating a PR with suggested changes?

**Comment by odow** [comment] 2020-09-10 20:05
Closed by https://github.com/jump-dev/SCS.jl/pull/195

**Closed by odow** 2020-09-10 20:05 UTC
